apptest/urls.py
from django.urls import path
from apptest import appviews

urlpatterns = [
    path('appcase_manage/', appviews.appcase_manage, name='appcase_manage'),
    path('appcasestep_manage/', appviews.appcasesetp_manage, name='appcasestep_manage'),
    path('appcasesearch/', appviews.appcasesearch, name='appcasesearch'),
    path('appstepsearch/', appviews.appstepsearch, name='appstepsearch'),
]

autotest/urls.py
from django.contrib import admin
from django.urls import path, include
from bug import bugviews
from sets import setsviews
from user.userviews import home

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls,),
    path('user/', include('user.urls')),
    path('apitest/', include('apitest.urls')),
    path('apptest/', include('apptest.urls')),
    path('webtest/', include('webtest.urls')),
    path('product/', include('product.urls')),
    path('bug_manage/', bugviews.bug_manage),
    path('sets_manage/', setsviews.sets_manage),
    path('sets_user/', setsviews.set_user),
]

user/urls.py
from django.urls import path
from user import userviews

urlpatterns = [
    path('login/', userviews.login, name='login'),
    path('home/', userviews.home, name='home'),
    path('logout/', userviews.logout, name='logout'),
    path('register/', userviews.register, name='register'),
    path('get_code/', userviews.get_code, name='get_code'),
    path('change_pwd/', userviews.change_psw, name='change_pwd'),
    path('welcome/', userviews.welcome, name='welcome')
]

apptest/models.py
from django.db import models


# Create your models here.
class Appcase(models.Model):
    Product = models.ForeignKey(
        'product.Product', on_delete=models.CASCADE, null=True)  # 关联产品id
    appcasename = models.CharField('用例名称', max_length=200)  # 测试用例名称
    apptestresult = models.BooleanField('测试结果')  # 测试结果
    apptester = models.CharField('测试负责人', max_length=16)  # 执行人
    create_time = models.DateTimeField('创建时间', auto_now=True)  # 创建时间-自动获取当前时间

    class Meta:
        verbose_name = 'app测试用例'
        verbose_name_plural = 'app测试用例'

    def __str__(self):
        return self.appcasename


class Appcasestep(models.Model):
    Appcase = models.ForeignKey('Appcase', on_delete=models.CASCADE)  # 关联接口id
    appteststep = models.CharField('测试步聚', max_length=200)  # 测试步聚
    apptestobjname = models.CharField('测试对象名称描述', max_length=200)  # 测试对象名称描述
    appfindmethod = models.CharField('定位方式', max_length=200)  # 定位方式
    appevelement = models.CharField('控件元素', max_length=800)  # 控件元素
    appoptmethod = models.CharField('操作方法', max_length=200)  # 操作方法
    apptestdata = models.CharField('测试数据', max_length=200, null=True)  # 测试数据
    appassertdata = models.CharField('验证数据', max_length=200)  # 验证数据
    apptestresult = models.BooleanField('测试结果')  # 测试结果
    create_time = models.DateTimeField('创建时间', auto_now=True)  # 创建时间-自动获取当前时间

    def __str__(self):
        return self.appteststep

apptest/templates/appcase_manage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>自动化测试平台</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
</head>
<body role="document">
    <!-- 导航栏-->
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top" style="border-radius: 0">
        <div class="container justify-content-end"> 
            <ul class="navbar-nav">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="apis"><a style="color: gray;font-size: 18px" href="/apitest/apis_manage/" target="mainFrame">单一接口</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="apitest"><a style="color: gray;font-size: 18px" href="/apitest/apitest_manage/" target="mainFrame">流程接口</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="appcase"><a style="color: white;font-size: 18px" href="/apptest/appcase_manage/" target="mainFrame">app用例</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="webcase"><a style="color: gray;font-size: 18px" href="/webtest/webcase_manage/" target="mainFrame">web用例</a></li>
            </ul>
        </div>
        <div class="container justify-content-end">
            <ul class="navbar-nav" style="font-size:18px;">
                <li class="nav-item"><a class="nav-link active" href="#">
                    <i class="glyphicon glyphicon-user"></i>&nbsp;{{user}}</a></li>
                <li class="nav-item"><a class="nav-link" href="/user/logout/" target="_parent">退出</a></li>
            </ul>
        </div>
    </nav>
    <!--搜索-->
    <div class="page-header" style="padding: 40px 20px 0">
        <form action="/apptest/appcasesearch/" method="GET" "navbar-form">
            <input type="search" name="appcasename" placeholder="名称" required>
            <button type="submit">搜索</button>
            <!-- 增加app测试用例-->
        <div style="float:right;width:65%">
            <select name="Appcase" id="id_Appcase">
                <option value="" selected>------app测试用例------</option>
                {% for appcase in appcases %}
                <option value="">{{ appcase.appcasename }}</option>
                {% endfor %}
            </select>
            <a class="related-widget-wrapper-link change-related" 
                id="change_id_Appcase" 
                data-href-template="/admin/apptest/appcase/__fk__/change/?_to_field=id&amp;_popup=1" 
                title="更改选中的测试用例">
                <img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
            </a>
            <a class="related-widget-wrapper-link add-related" 
                id="add_id_Appcase" 
                href="/admin/apptest/appcase/add/?_to_field=id&amp;_popup=1" 
                title="增加另一个 测试用例">
                <img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
            </a>
        </div>
        </form>
    </div>
    <!--流程接口步骤-->
    <div class="row" style="font-size: 14px">
        <div class="col-md-11">
            <table class="table table-hover">
                <thead class="thead-light">
                    <tr>
                        <th>ID</th>
                        <th>产品</th>
                        <th>测试用例名称</th>
                        <th>测试结果</th>
                        <th>负责人</th>
                        <th>时间</th>
                        <th>查看</th>
                        <th>编辑</th>
                        <th>删除</th>
                    </tr>
                </thead>
                <tbody>
                    {% for appcase in appcases %}
                    <tr>
                        <td>{{ appcase.id }}</td>
                        <td>{{ appcase.Product.productname }}</td>
                        <td>{{ appcase.appcasename }}</td>
                        <td>{% if appcase.apptestresult == 1 %}
                            <a style='color:green'>{{ appcase.apptestresult }}</a> 
                            {% else %}
                            <a style='color:red'>{{ appcase.apptestresult }}</a> 
                            {% endif %}
                        </td>
                        <td>{{ appcase.apptester }}</td>
                        <td>{{ appcase.create_time }}</td>
                        <td><a href="{% url "appcasestep_manage" %}?appcase.id={{ appcase.id  }} ">
                            <img src="/static/admin/img/icon-yes.svg"/>
                            </a>
                        </td> 
                        <td><a style='color:light blue' 
                            class="related-widget-wrapper-link add-related" 
                            id="add_id_Appcase" 
                            href="/admin/apptest/appcase/{{ appcase.id  }}/change/?_to_field=id&_popup=1">
                            <img src="/static/admin/img/icon-changelink.svg"/>
                            </a>
                        </td>
                        <td><a style='color:light blue' 
                            class="related-widget-wrapper-link add-related" 
                            id="add_id_Appcase" 
                            href="/admin/apptest/appcase/{{ appcase.id  }}/delete/?_to_field=id&_popup=1">
                            <img src="/static/admin/img/icon-deletelink.svg"/>
                            </a>
                        </td>
                    <tr />
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!--统计和翻页功能-->
    <span style="position:absolute; right:100px; bottom:30px;">   {# 把翻页功能固定显示在右下角#}
        <div style="position:absolute; right:500px; bottom:25px; width: 100px;">
        共{{ appcasecounts }}条记录 {# 前端读取定义的变量#}
        </div>
        
        <div class="container">
            <ul class="pagination" id="pager">
                  {# 上一页链接开始#}
                {% if appcases.has_previous %}
                    {#  如果有上一页则正常显示上一页链接#}
                    <li class="previous"><a href="/apptest/appcase_manage/?page={{ appcases.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
                {% else %}
                    <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
                {% endif %}
                {# 上一页链接开始#}
                
                {% for num in appcases.paginator.page_range %}
                 
                    {% if num == currentPage %}
                        <li class="item active"><a href="/apptest/appcase_manage/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#} 
                    {% else %}
                        <li class="item"><a href="/apptest/appcase_manage/?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                
                {# 下一页链接开始#}
                {% if appcases.has_next %} {#  如果有下一页则正常显示下一页链接#}
                    <li class="next"><a href="/apptest/appcase_manage/?page={{ appcases.next_page_number }}">下一页</a></li>
                {% else %}
                    <li class="next disabled"><a href="#">下一页</a></li>
                {% endif %}
                {# 下一页链接结束#}
            </ul>
        </div>
    </span>
</body>
</html>

apptest/templates/appcasestep_manage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>自动化测试平台</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
</head>
<body role="document">
    <!-- 导航栏-->
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top" style="border-radius: 0">
        <div class="container justify-content-end"> 
            <ul class="navbar-nav">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="apis"><a style="color: gray;font-size: 18px" href="/apitest/apis_manage/" target="mainFrame">单一接口</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="apitest"><a style="color: gray;font-size: 18px" href="/apitest/apitest_manage/" target="mainFrame">流程接口</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="appcase"><a style="color: white;font-size: 18px" href="/apptest/appcase_manage/" target="mainFrame">app用例</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="webcase"><a style="color: gray;font-size: 18px" href="/webtest/webcase_manage/" target="mainFrame">web用例</a></li>
            </ul>
        </div>
        <div class="container justify-content-end">
            <ul class="navbar-nav" style="font-size:18px;">
                <li class="nav-item"><a class="nav-link active" href="#">
                    <i class="glyphicon glyphicon-user"></i>&nbsp;{{user}}</a></li>
                <li class="nav-item"><a class="nav-link" href="/user/logout/" target="_parent">退出</a></li>
            </ul>
        </div>
    </nav>
    <!--搜索-->
    <div class="page-header" style="padding: 40px 20px 0">
        <form action="/appstepsearch/" method="GET" "navbar-form">
            <input type="search" name="appteststep" placeholder="名称" required>
            <button type="submit">搜索</button>
        </form>
    </div>
    <!--流程接口步骤-->
    <div class="row" style="font-size: 14px">
        <div class="col-md-11">
            <table class="table table-hover">
                <thead class="thead-light">
                    <tr> 
                        <th>产品</th>
                        <th>所属用例</th>
                        <th>步聚</th>
                        <th>定位方式</th>
                        <th>控件元素</th>
                        <th>操作方法</th>
                        <th>测试数据</th>
                        <th>验证数据</th>
                        <th>测试结果</th>
                        <th>时间</th>
                    </tr>
                </thead>
                <tbody>
                    {% for appcasestep in appcasesteps %}
                    <tr>
                    {% if appcasestep.Appcase.id == appcase.id %}
                    <td>{{ appcasestep.Appcase.Product.productname }}</td>
                    <td>case_{{ appcasestep.Appcase.id }}_{{ appcasestep.Appcase.appcasename }}</td>
                    <td>{{ appcasestep.appteststep }}:{{ appcasestep.apptestobjname }}</td>
                    <td>{{ appcasestep.appfindmethod }}</td>
                    <td>{{ appcasestep.appevelement }}</td>
                    <td>{{ appcasestep.appoptmethod }}</td>
                    <td>{{ appcasestep.apptestdata }}</td>
                    <td>{{ appcasestep.appassertdata }}</td>
                    <td>{% if appcasestep.apptestresult == 1 %}
                        <a style='color:green'>{{ appcasestep.apptestresult }}</a> 
                        {% else %}
                        <a style='color:red'>{{ appcasestep.apptestresult }}</a> 
                        {% endif %}
                    </td>
                    <td>{{ appcasestep.create_time }}</td>
                    {% else %}
                    {% endif %}
                    {% endfor %}
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div style="width: 100px;margin: 0 auto;">
        <td>
            <a style='color:light blue'  href="../appcase_manage/" >
            <img src="/static/admin/img/icon-yes.svg" alt="返回"/>返回
            </a>
            </td>
            
            <td>
            <a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Appcase" href="/admin/apptest/appcase/{{ appcase.id  }}/change/?_to_field=id&_popup=1">
            <img src="/static/admin/img/icon-changelink.svg"/>编辑</a>
        </td>
    </div>
</body>
</html>