autotest/urls.py
from django.contrib import admin
from django.urls import path, include
from bug import bugviews
from sets import setsviews
from user.userviews import home

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls,),
    path('user/', include('user.urls')),
    path('apitest/', include('apitest.urls')),
    path('apptest/', include('apptest.urls')),
    path('webtest/', include('webtest.urls')),
    path('product/', include('product.urls')),
    path('bug_manage/', bugviews.bug_manage),
    path('sets_manage/', setsviews.sets_manage),
    path('sets_user/', setsviews.set_user),
]

user/urls.py
from django.urls import path
from user import userviews

urlpatterns = [
    path('login/', userviews.login, name='login'),
    path('home/', userviews.home, name='home'),
    path('logout/', userviews.logout, name='logout'),
    path('register/', userviews.register, name='register'),
    path('get_code/', userviews.get_code, name='get_code'),
    path('change_pwd/', userviews.change_psw, name='change_pwd'),
    path('welcome/', userviews.welcome, name='welcome')
]

webtest/urls.py
from django.urls import path
from webtest import webviews

urlpatterns = [
    path('webcase_manage/', webviews.webcase_manage, name='webcase_manage'),
    path('webcasestep_manage/', webviews.webcasesetp_manage, name='webcasestep_manage'),
    path('webcasesearch/', webviews.webcasesearch, name='webcasesearch'),
    path('webstepsearch/', webviews.webstepsearch, name='webstepsearch'),
]

webtest/models.py
from django.db import models


# Create your models here.
class Webcase(models.Model):

    product = models.ForeignKey(
        'product.Product', on_delete=models.CASCADE, null=True)  # 关联产品id
    webcasename = models.CharField('用例名称', max_length=200)  # 测试用例名称
    webtestresult = models.BooleanField('测试结果')  # 测试结果
    webtester = models.CharField('测试负责人', max_length=16)  # 测试负责人
    create_time = models.DateTimeField('创建时间', auto_now=True)  # 创建时间-自动获取当前时间

    class Meta:
        verbose_name = 'web测试用例'
        verbose_name_plural = 'web测试用例'

    def __str__(self):
        return self.webcasename


class Webcasestep(models.Model):

    Webcase = models.ForeignKey(Webcase, on_delete=models.CASCADE)  # 关联接口id
    webteststep = models.CharField('测试步聚', max_length=200)  # 测试步聚
    webtestobjname = models.CharField('测试对象名称描述', max_length=200)  # 测试对象名称描述
    webfindmethod = models.CharField('定位方式', max_length=200)  # 定位方式
    webevelement = models.CharField('控件元素', max_length=800)  # 控件元素
    weboptmethod = models.CharField('操作方法', max_length=200)  # 操作方法
    webtestdata = models.CharField('测试数据', max_length=200, null=True)  # 测试数据
    webassertdata = models.CharField('验证数据', max_length=200)  # 验证数据
    webtestresult = models.BooleanField('测试结果')  # 测试结果
    create_time = models.DateTimeField('创建时间', auto_now=True)  # 创建时间-自动获取当前时间

    def __str__(self):
        return self.webteststep

webtest/templates/webcase_manage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>自动化测试平台</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
</head>
<body role="document">
    <!-- 导航栏-->
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top" style="border-radius: 0">
        <div class="container justify-content-end"> 
            <ul class="navbar-nav">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="apis"><a style="color: gray;font-size: 18px" href="/apitest/apis_manage/" target="mainFrame">单一接口</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="apitest"><a style="color: gray;font-size: 18px" href="/apitest/apitest_manage/" target="mainFrame">流程接口</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="appcase"><a style="color: gray;font-size: 18px" href="/apptest/appcase_manage/" target="mainFrame">app用例</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="webcase"><a style="color: white;font-size: 18px" href="/webtest/webcase_manage/" target="mainFrame">web用例</a></li>
            </ul>
        </div>
        <div class="container justify-content-end">
            <ul class="navbar-nav" style="font-size:18px;">
                <li class="nav-item"><a class="nav-link active" href="#">
                    <i class="glyphicon glyphicon-user"></i>&nbsp;{{user}}</a></li>
                <li class="nav-item"><a class="nav-link" href="/user/logout/" target="_parent">退出</a></li>
            </ul>
        </div>
    </nav>
    <!--搜索-->
    <div class="page-header" style="padding: 40px 20px 0">
        <form action="/webtest/webcasesearch/" method="GET" "navbar-form">
            <input type="search" name="webcasename" placeholder="名称" required>
            <button type="submit">搜索</button>
            <!-- 增加web测试用例-->
<div style="float:right;width:65%">

        <select name="Webcase" id="id_Webcase">
            <option value="" selected>----web测试用例----</option>
            {% for webcase in webcases %}
            <option value="">{{ webcase.webcasename }}</option>
            {% endfor %}
        </select>
        <a class="related-widget-wrapper-link change-related" id="change_id_Webcase" data-href-template="/admin/webtest/webcase/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
            <img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
        </a>
        <a class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="/admin/webtest/webcase/add/?_to_field=id&amp;_popup=1" title="增加另一个 测试用例">
            <img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
        </a>
        </div>
        </form>
    </div>
    <!--流程接口步骤-->
    <div class="row" style="font-size: 14px">
        <div class="col-md-11">
            <table class="table table-hover">
                <thead class="thead-light">
                    <tr>
                        <th>ID</th>
                        <th>产品</th>
                        <th>测试用例名称</th>
                        <th>测试结果</th>
                        <th>测试负责人</th>
                        <th>时间</th>
                        <th>查看</th>
                        <th>编辑</th>
                        <th>删除</th>
                    </tr>
                </thead>
                <tbody>
                    {% for webcase in webcases %}
                    <tr>
                        <td>{{ webcase.id }}</td>
                        <td>{{ webcase.product.productname }}</td>
                        <td>{{ webcase.webcasename }}</td>
                        <td>{% if webcase.webtestresult == 1 %}
                                <a style='color:green'>{{ webcase.webtestresult }}</a> 
                                {% else %}
                                <a style='color:red'>{{ webcase.webtestresult }}</a> 
                                {% endif %}
                        </td>
                        <td>{{ webcase.webtester }}</td>
                        <td>{{ webcase.create_time }}</td>
                        <td><a href="{% url "webcasestep_manage" %}?webcase.id={{ webcase.id  }} ">
                            <img src="/static/admin/img/icon-yes.svg"/>
                            </a>
                        </td> 
                        <td><a style='color:light blue' 
                            class="related-widget-wrapper-link add-related" 
                            id="add_id_Webcase" 
                            href="/admin/webtest/webcase/{{ webcase.id  }}/change/?_to_field=id&_popup=1">
                            <img src="/static/admin/img/icon-changelink.svg"/>
                            </a>
                        </td>
                        <td><a style='color:light blue' 
                            class="related-widget-wrapper-link add-related" 
                            id="add_id_Webcase" 
                            href="/admin/webtest/webcase/{{ webcase.id  }}/delete/?_to_field=id&_popup=1">
                            <img src="/static/admin/img/icon-deletelink.svg"/>
                        </a></td>
                    <tr />
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!--统计和翻页功能-->
    <span style="position:absolute; right:100px; bottom:30px;">   {# 把翻页功能固定显示在右下角#}
        <div style="position:absolute; right:500px; bottom:25px; width: 100px;">
        共{{ webcasecounts }}条记录 {# 前端读取定义的变量#}
        </div>
        <div class="container">
            <ul class="pagination" id="pager">
                  {# 上一页链接开始#}
                {% if webcases.has_previous %}
                    {#  如果有上一页则正常显示上一页链接#}
                    <li class="previous"><a href="/webtest/webcase_manage/?page={{ webcases.previous_page_number }}">上一页</a></li>    {#  上一页标签 #}
                {% else %}
                    <li class="previous disabled"><a href="#">上一页</a></li> {# 如果当前不存在上一页则上一页的链接不可点击#}
                {% endif %}
                {# 上一页链接开始#}
                
                {% for num in webcases.paginator.page_range %}
                 
                    {% if num == currentPage %}
                        <li class="item active"><a href="/webtest/webcase_manage/?page={{ num }}">{{ num }}</a></li> {#显示当页数链接#} 
                    {% else %}
                        <li class="item"><a href="/webtest/webcase_manage/?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                
                {# 下一页链接开始#}
                {% if webcases.has_next %} {#  如果有下一页则正常显示下一页链接#}
                    <li class="next"><a href="/webtest/webcase_manage/?page={{ webcases.next_page_number }}">下一页</a></li>
                {% else %}
                    <li class="next disabled"><a href="#">下一页</a></li>
                {% endif %}
                {# 下一页链接结束#}
            </ul>
        </div>
    </span>
</body>
</html>

webtest/templates/webcasestep_manage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>自动化测试平台</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
</head>
<body role="document">
    <!-- 导航栏-->
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top" style="border-radius: 0">
        <div class="container justify-content-end"> 
            <ul class="navbar-nav">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="apis"><a style="color: gray;font-size: 18px" href="/apitest/apis_manage/" target="mainFrame">单一接口</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="apitest"><a style="color: gray;font-size: 18px" href="/apitest/apitest_manage/" target="mainFrame">流程接口</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="appcase"><a style="color: gray;font-size: 18px" href="/apptest/appcase_manage/" target="mainFrame">app用例</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active" id="webcase"><a style="color: white;font-size: 18px" href="/webtest/webcase_manage/" target="mainFrame">web用例</a></li>
            </ul>
        </div>
        <div class="container justify-content-end">
            <ul class="navbar-nav" style="font-size:18px;">
                <li class="nav-item"><a class="nav-link active" href="#">
                    <i class="glyphicon glyphicon-user"></i>&nbsp;{{user}}</a></li>
                <li class="nav-item"><a class="nav-link" href="/user/logout/" target="_parent">退出</a></li>
            </ul>
        </div>
    </nav>
    <!--搜索-->
    <div class="page-header" style="padding: 40px 20px 0">
        <form action="/webtest/webstepsearch/" method="GET" "navbar-form">
            <input type="search" name="webteststep" placeholder="名称" required>
            <button type="submit">搜索</button>
        </form>
    </div>
    <!--流程接口步骤-->
    <div class="row" style="font-size: 14px">
        <div class="col-md-11">
            <table class="table table-hover">
                <thead class="thead-light">
                    <tr> 
                        <th>产品</th>
                        <th>所属用例</th>
                        <th>步聚</th>
                        <th>定位方式</th>
                        <th>控件元素</th>
                        <th>操作方法</th>
                        <th>测试数据</th>
                        <th>验证数据</th>
                        <th>测试结果</th>
                        <th>时间</th>
                    </tr>
                </thead>
                <tbody>
                    {% for webcasestep in webcasesteps %}
                    <tr>
                    {% if webcasestep.Webcase.id == webcase.id %}
                    <td>{{ webcasestep.Webcase.product.productname }}</td>
                    <td>case_{{ webcasestep.Webcase.id }}_{{ webcasestep.Webcase.webcasename }}</td>
                    <td>{{ webcasestep.webteststep }}:{{ webcasestep.webtestobjname }}</td>
                    <td>{{ webcasestep.webfindmethod }}</td>
                    <td>{{ webcasestep.webevelement }}</td>
                    <td>{{ webcasestep.weboptmethod }}</td>
                    <td>{{ webcasestep.webtestdata }}</td>
                    <td>{{ webcasestep.webassertdata }}</td>
                    <td>{% if webcasestep.webtestresult == 1 %}
                        <a style='color:green'>{{ webcasestep.webtestresult }}</a> 
                        {% else %}
                        <a style='color:red'>{{ webcasestep.webtestresult }}</a> 
                        {% endif %}
                    </td>
                    <td>{{ webcasestep.create_time }}</td> 
                    {% else %}
                    {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div style="width: 100px;margin: 0 auto;">
        <td>
            <a style='color:light blue'  href="../webcase_manage/" >
            <img src="/static/admin/img/icon-yes.svg" alt="返回"/>返回
            </a>
            </td>
            
            <td>
            <a style='color:light blue' class="related-widget-wrapper-link add-related" id="add_id_Webtest" href="/admin/webtest/webcase/{{ webcase.id  }}/change/?_to_field=id&_popup=1">
            <img src="/static/admin/img/icon-changelink.svg"/>编辑</a>
        </td>
    </div>
</body>
</html>